Rdiscrowd 7532 grafana dash link
bloomberg/pybossa-default-theme pull request #462
Opened 2024-08-14 14:01 UTC by n00rsy

*Issue number of the reported bug or feature request: [RDISCROWD-7532](https://jira.prod.bloomberg.com/browse/RDISCROWD-7532)*

**Describe your changes**
 - add a link to grafana POC dashboard from GIGwork project stats page

**Testing performed**
Tested locally

2024-08-14 20:29 UTC, kbecker42 approved these changes

2024-08-14 20:38 UTC, kbecker42 requested changes

2024-08-14 20:38 UTC, kbecker42 commented on templates/projects/non_stats.html
> +            <a class="btn btn-primary" target="_blank" href="https://grafana.prod.bloomberg.com/d/f59623f5-0ab2-4849-80d3-f4ef8bda7259/poc-crowd-task-metrics?var-project_id={{project.id}}&var-task_so
This url should be moved into `settings_local.py` and populated similar to the following:

```html
{% if config.get('DASHBOARD_URL') %}
   {% dashboard_url = config.get('DASHBOARD_URL') + "var-project_id=" + project.id + "&var-task_source=GIGWORK_" + ("PRIV" if private_instance else "PUBLIC") %}
   <div class="row" style="margin-top: 2em;" id="grafana-link">
      <a class="btn btn-primary" target="_blank" href="{{ dashboard_url }}">Metrics Dashboard</a>
   </div>
{% endif %}
```

2024-08-15 14:02 UTC, n00rsy commented on templates/projects/non_stats.html
> +            <a class="btn btn-primary" target="_blank" href="https://grafana.prod.bloomberg.com/d/f59623f5-0ab2-4849-80d3-f4ef8bda7259/poc-crowd-task-metrics?var-project_id={{project.id}}&var-task_so
updated via 5537332

2024-08-15 14:07 UTC, kbecker42 commented on templates/projects/non_stats.html
> +                <a class="btn btn-primary" target="_blank" href="{{dashboard_url}}">Grafana Metrics Dashboard</a>
Could we change the label to "Metrics Dashboard" to be more generic with all types of projects? Thank you .

2024-08-15 14:25 UTC, merged